// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.haotu369.tio.im.common.packets;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
   * </pre>
   *
   * <code>string addressDetail = 1;</code>
   */
  java.lang.String getAddressDetail();
  /**
   * <pre>
   * 地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
   * </pre>
   *
   * <code>string addressDetail = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressDetailBytes();

  /**
   * <pre>
   * 330106
   * </pre>
   *
   * <code>string addressCode = 2;</code>
   */
  java.lang.String getAddressCode();
  /**
   * <pre>
   * 330106
   * </pre>
   *
   * <code>string addressCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressCodeBytes();

  /**
   * <pre>
   * 浙江省
   * </pre>
   *
   * <code>string province = 3;</code>
   */
  java.lang.String getProvince();
  /**
   * <pre>
   * 浙江省
   * </pre>
   *
   * <code>string province = 3;</code>
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <pre>
   * 杭州
   * </pre>
   *
   * <code>string city = 4;</code>
   */
  java.lang.String getCity();
  /**
   * <pre>
   * 杭州
   * </pre>
   *
   * <code>string city = 4;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <pre>
   * 0571
   * </pre>
   *
   * <code>string cityCode = 5;</code>
   */
  java.lang.String getCityCode();
  /**
   * <pre>
   * 0571
   * </pre>
   *
   * <code>string cityCode = 5;</code>
   */
  com.google.protobuf.ByteString
      getCityCodeBytes();

  /**
   * <pre>
   * 西湖区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  java.lang.String getDistrict();
  /**
   * <pre>
   * 西湖区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  com.google.protobuf.ByteString
      getDistrictBytes();

  /**
   * <pre>
   * 古荡街区
   * </pre>
   *
   * <code>string township = 7;</code>
   */
  java.lang.String getTownship();
  /**
   * <pre>
   * 古荡街区
   * </pre>
   *
   * <code>string township = 7;</code>
   */
  com.google.protobuf.ByteString
      getTownshipBytes();

  /**
   * <pre>
   * 天目山路
   * </pre>
   *
   * <code>string street = 8;</code>
   */
  java.lang.String getStreet();
  /**
   * <pre>
   * 天目山路
   * </pre>
   *
   * <code>string street = 8;</code>
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <pre>
   * 307号
   * </pre>
   *
   * <code>string streetNumber = 9;</code>
   */
  java.lang.String getStreetNumber();
  /**
   * <pre>
   * 307号
   * </pre>
   *
   * <code>string streetNumber = 9;</code>
   */
  com.google.protobuf.ByteString
      getStreetNumberBytes();
}
