// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.haotu369.tio.im.common.packets;

/**
 * <pre>
 **
 * 地址
 * </pre>
 *
 * Protobuf type {@code Address}
 */
public  final class Address extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Address)
    AddressOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Address.newBuilder() to construct.
  private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Address() {
    addressDetail_ = "";
    addressCode_ = "";
    province_ = "";
    city_ = "";
    cityCode_ = "";
    district_ = "";
    township_ = "";
    street_ = "";
    streetNumber_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Address(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            addressDetail_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            addressCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            province_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            cityCode_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            district_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            township_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            street_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            streetNumber_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.haotu369.tio.im.common.packets.Chat.internal_static_Address_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.haotu369.tio.im.common.packets.Chat.internal_static_Address_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.haotu369.tio.im.common.packets.Address.class, com.haotu369.tio.im.common.packets.Address.Builder.class);
  }

  public static final int ADDRESSDETAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object addressDetail_;
  /**
   * <pre>
   * 地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
   * </pre>
   *
   * <code>string addressDetail = 1;</code>
   */
  public java.lang.String getAddressDetail() {
    java.lang.Object ref = addressDetail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addressDetail_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
   * </pre>
   *
   * <code>string addressDetail = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAddressDetailBytes() {
    java.lang.Object ref = addressDetail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addressDetail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESSCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object addressCode_;
  /**
   * <pre>
   * 330106
   * </pre>
   *
   * <code>string addressCode = 2;</code>
   */
  public java.lang.String getAddressCode() {
    java.lang.Object ref = addressCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addressCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 330106
   * </pre>
   *
   * <code>string addressCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAddressCodeBytes() {
    java.lang.Object ref = addressCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addressCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVINCE_FIELD_NUMBER = 3;
  private volatile java.lang.Object province_;
  /**
   * <pre>
   * 浙江省
   * </pre>
   *
   * <code>string province = 3;</code>
   */
  public java.lang.String getProvince() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      province_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 浙江省
   * </pre>
   *
   * <code>string province = 3;</code>
   */
  public com.google.protobuf.ByteString
      getProvinceBytes() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      province_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_FIELD_NUMBER = 4;
  private volatile java.lang.Object city_;
  /**
   * <pre>
   * 杭州
   * </pre>
   *
   * <code>string city = 4;</code>
   */
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 杭州
   * </pre>
   *
   * <code>string city = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITYCODE_FIELD_NUMBER = 5;
  private volatile java.lang.Object cityCode_;
  /**
   * <pre>
   * 0571
   * </pre>
   *
   * <code>string cityCode = 5;</code>
   */
  public java.lang.String getCityCode() {
    java.lang.Object ref = cityCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cityCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 0571
   * </pre>
   *
   * <code>string cityCode = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCityCodeBytes() {
    java.lang.Object ref = cityCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cityCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISTRICT_FIELD_NUMBER = 6;
  private volatile java.lang.Object district_;
  /**
   * <pre>
   * 西湖区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  public java.lang.String getDistrict() {
    java.lang.Object ref = district_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      district_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 西湖区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDistrictBytes() {
    java.lang.Object ref = district_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      district_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOWNSHIP_FIELD_NUMBER = 7;
  private volatile java.lang.Object township_;
  /**
   * <pre>
   * 古荡街区
   * </pre>
   *
   * <code>string township = 7;</code>
   */
  public java.lang.String getTownship() {
    java.lang.Object ref = township_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      township_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 古荡街区
   * </pre>
   *
   * <code>string township = 7;</code>
   */
  public com.google.protobuf.ByteString
      getTownshipBytes() {
    java.lang.Object ref = township_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      township_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREET_FIELD_NUMBER = 8;
  private volatile java.lang.Object street_;
  /**
   * <pre>
   * 天目山路
   * </pre>
   *
   * <code>string street = 8;</code>
   */
  public java.lang.String getStreet() {
    java.lang.Object ref = street_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      street_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 天目山路
   * </pre>
   *
   * <code>string street = 8;</code>
   */
  public com.google.protobuf.ByteString
      getStreetBytes() {
    java.lang.Object ref = street_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      street_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREETNUMBER_FIELD_NUMBER = 9;
  private volatile java.lang.Object streetNumber_;
  /**
   * <pre>
   * 307号
   * </pre>
   *
   * <code>string streetNumber = 9;</code>
   */
  public java.lang.String getStreetNumber() {
    java.lang.Object ref = streetNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      streetNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 307号
   * </pre>
   *
   * <code>string streetNumber = 9;</code>
   */
  public com.google.protobuf.ByteString
      getStreetNumberBytes() {
    java.lang.Object ref = streetNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      streetNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAddressDetailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addressDetail_);
    }
    if (!getAddressCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addressCode_);
    }
    if (!getProvinceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, province_);
    }
    if (!getCityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, city_);
    }
    if (!getCityCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cityCode_);
    }
    if (!getDistrictBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, district_);
    }
    if (!getTownshipBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, township_);
    }
    if (!getStreetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, street_);
    }
    if (!getStreetNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, streetNumber_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAddressDetailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addressDetail_);
    }
    if (!getAddressCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, addressCode_);
    }
    if (!getProvinceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, province_);
    }
    if (!getCityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, city_);
    }
    if (!getCityCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cityCode_);
    }
    if (!getDistrictBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, district_);
    }
    if (!getTownshipBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, township_);
    }
    if (!getStreetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, street_);
    }
    if (!getStreetNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, streetNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.haotu369.tio.im.common.packets.Address)) {
      return super.equals(obj);
    }
    com.haotu369.tio.im.common.packets.Address other = (com.haotu369.tio.im.common.packets.Address) obj;

    boolean result = true;
    result = result && getAddressDetail()
        .equals(other.getAddressDetail());
    result = result && getAddressCode()
        .equals(other.getAddressCode());
    result = result && getProvince()
        .equals(other.getProvince());
    result = result && getCity()
        .equals(other.getCity());
    result = result && getCityCode()
        .equals(other.getCityCode());
    result = result && getDistrict()
        .equals(other.getDistrict());
    result = result && getTownship()
        .equals(other.getTownship());
    result = result && getStreet()
        .equals(other.getStreet());
    result = result && getStreetNumber()
        .equals(other.getStreetNumber());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADDRESSDETAIL_FIELD_NUMBER;
    hash = (53 * hash) + getAddressDetail().hashCode();
    hash = (37 * hash) + ADDRESSCODE_FIELD_NUMBER;
    hash = (53 * hash) + getAddressCode().hashCode();
    hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
    hash = (53 * hash) + getProvince().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + CITYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getCityCode().hashCode();
    hash = (37 * hash) + DISTRICT_FIELD_NUMBER;
    hash = (53 * hash) + getDistrict().hashCode();
    hash = (37 * hash) + TOWNSHIP_FIELD_NUMBER;
    hash = (53 * hash) + getTownship().hashCode();
    hash = (37 * hash) + STREET_FIELD_NUMBER;
    hash = (53 * hash) + getStreet().hashCode();
    hash = (37 * hash) + STREETNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getStreetNumber().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.haotu369.tio.im.common.packets.Address parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.haotu369.tio.im.common.packets.Address parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Address parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.haotu369.tio.im.common.packets.Address parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Address parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.haotu369.tio.im.common.packets.Address parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Address parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.haotu369.tio.im.common.packets.Address parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Address parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.haotu369.tio.im.common.packets.Address parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Address parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.haotu369.tio.im.common.packets.Address parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.haotu369.tio.im.common.packets.Address prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 地址
   * </pre>
   *
   * Protobuf type {@code Address}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Address)
      com.haotu369.tio.im.common.packets.AddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haotu369.tio.im.common.packets.Chat.internal_static_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haotu369.tio.im.common.packets.Chat.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haotu369.tio.im.common.packets.Address.class, com.haotu369.tio.im.common.packets.Address.Builder.class);
    }

    // Construct using com.haotu369.tio.im.common.packets.Address.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      addressDetail_ = "";

      addressCode_ = "";

      province_ = "";

      city_ = "";

      cityCode_ = "";

      district_ = "";

      township_ = "";

      street_ = "";

      streetNumber_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.haotu369.tio.im.common.packets.Chat.internal_static_Address_descriptor;
    }

    public com.haotu369.tio.im.common.packets.Address getDefaultInstanceForType() {
      return com.haotu369.tio.im.common.packets.Address.getDefaultInstance();
    }

    public com.haotu369.tio.im.common.packets.Address build() {
      com.haotu369.tio.im.common.packets.Address result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.haotu369.tio.im.common.packets.Address buildPartial() {
      com.haotu369.tio.im.common.packets.Address result = new com.haotu369.tio.im.common.packets.Address(this);
      result.addressDetail_ = addressDetail_;
      result.addressCode_ = addressCode_;
      result.province_ = province_;
      result.city_ = city_;
      result.cityCode_ = cityCode_;
      result.district_ = district_;
      result.township_ = township_;
      result.street_ = street_;
      result.streetNumber_ = streetNumber_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.haotu369.tio.im.common.packets.Address) {
        return mergeFrom((com.haotu369.tio.im.common.packets.Address)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.haotu369.tio.im.common.packets.Address other) {
      if (other == com.haotu369.tio.im.common.packets.Address.getDefaultInstance()) return this;
      if (!other.getAddressDetail().isEmpty()) {
        addressDetail_ = other.addressDetail_;
        onChanged();
      }
      if (!other.getAddressCode().isEmpty()) {
        addressCode_ = other.addressCode_;
        onChanged();
      }
      if (!other.getProvince().isEmpty()) {
        province_ = other.province_;
        onChanged();
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (!other.getCityCode().isEmpty()) {
        cityCode_ = other.cityCode_;
        onChanged();
      }
      if (!other.getDistrict().isEmpty()) {
        district_ = other.district_;
        onChanged();
      }
      if (!other.getTownship().isEmpty()) {
        township_ = other.township_;
        onChanged();
      }
      if (!other.getStreet().isEmpty()) {
        street_ = other.street_;
        onChanged();
      }
      if (!other.getStreetNumber().isEmpty()) {
        streetNumber_ = other.streetNumber_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.haotu369.tio.im.common.packets.Address parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.haotu369.tio.im.common.packets.Address) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object addressDetail_ = "";
    /**
     * <pre>
     * 地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string addressDetail = 1;</code>
     */
    public java.lang.String getAddressDetail() {
      java.lang.Object ref = addressDetail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addressDetail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string addressDetail = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressDetailBytes() {
      java.lang.Object ref = addressDetail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addressDetail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string addressDetail = 1;</code>
     */
    public Builder setAddressDetail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      addressDetail_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string addressDetail = 1;</code>
     */
    public Builder clearAddressDetail() {
      
      addressDetail_ = getDefaultInstance().getAddressDetail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string addressDetail = 1;</code>
     */
    public Builder setAddressDetailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      addressDetail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object addressCode_ = "";
    /**
     * <pre>
     * 330106
     * </pre>
     *
     * <code>string addressCode = 2;</code>
     */
    public java.lang.String getAddressCode() {
      java.lang.Object ref = addressCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addressCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 330106
     * </pre>
     *
     * <code>string addressCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressCodeBytes() {
      java.lang.Object ref = addressCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addressCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 330106
     * </pre>
     *
     * <code>string addressCode = 2;</code>
     */
    public Builder setAddressCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      addressCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 330106
     * </pre>
     *
     * <code>string addressCode = 2;</code>
     */
    public Builder clearAddressCode() {
      
      addressCode_ = getDefaultInstance().getAddressCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 330106
     * </pre>
     *
     * <code>string addressCode = 2;</code>
     */
    public Builder setAddressCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      addressCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object province_ = "";
    /**
     * <pre>
     * 浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public Builder setProvince(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public Builder clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public Builder setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <pre>
     * 杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cityCode_ = "";
    /**
     * <pre>
     * 0571
     * </pre>
     *
     * <code>string cityCode = 5;</code>
     */
    public java.lang.String getCityCode() {
      java.lang.Object ref = cityCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cityCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 0571
     * </pre>
     *
     * <code>string cityCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCityCodeBytes() {
      java.lang.Object ref = cityCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 0571
     * </pre>
     *
     * <code>string cityCode = 5;</code>
     */
    public Builder setCityCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cityCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0571
     * </pre>
     *
     * <code>string cityCode = 5;</code>
     */
    public Builder clearCityCode() {
      
      cityCode_ = getDefaultInstance().getCityCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0571
     * </pre>
     *
     * <code>string cityCode = 5;</code>
     */
    public Builder setCityCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cityCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object district_ = "";
    /**
     * <pre>
     * 西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public java.lang.String getDistrict() {
      java.lang.Object ref = district_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        district_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDistrictBytes() {
      java.lang.Object ref = district_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        district_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public Builder setDistrict(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      district_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public Builder clearDistrict() {
      
      district_ = getDefaultInstance().getDistrict();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public Builder setDistrictBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      district_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object township_ = "";
    /**
     * <pre>
     * 古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public java.lang.String getTownship() {
      java.lang.Object ref = township_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        township_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTownshipBytes() {
      java.lang.Object ref = township_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        township_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public Builder setTownship(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      township_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public Builder clearTownship() {
      
      township_ = getDefaultInstance().getTownship();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public Builder setTownshipBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      township_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object street_ = "";
    /**
     * <pre>
     * 天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public Builder setStreet(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      street_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public Builder clearStreet() {
      
      street_ = getDefaultInstance().getStreet();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public Builder setStreetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      street_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object streetNumber_ = "";
    /**
     * <pre>
     * 307号
     * </pre>
     *
     * <code>string streetNumber = 9;</code>
     */
    public java.lang.String getStreetNumber() {
      java.lang.Object ref = streetNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 307号
     * </pre>
     *
     * <code>string streetNumber = 9;</code>
     */
    public com.google.protobuf.ByteString
        getStreetNumberBytes() {
      java.lang.Object ref = streetNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 307号
     * </pre>
     *
     * <code>string streetNumber = 9;</code>
     */
    public Builder setStreetNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      streetNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 307号
     * </pre>
     *
     * <code>string streetNumber = 9;</code>
     */
    public Builder clearStreetNumber() {
      
      streetNumber_ = getDefaultInstance().getStreetNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 307号
     * </pre>
     *
     * <code>string streetNumber = 9;</code>
     */
    public Builder setStreetNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      streetNumber_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Address)
  }

  // @@protoc_insertion_point(class_scope:Address)
  private static final com.haotu369.tio.im.common.packets.Address DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.haotu369.tio.im.common.packets.Address();
  }

  public static com.haotu369.tio.im.common.packets.Address getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Address>
      PARSER = new com.google.protobuf.AbstractParser<Address>() {
    public Address parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Address(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Address> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Address> getParserForType() {
    return PARSER;
  }

  public com.haotu369.tio.im.common.packets.Address getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

