// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.haotu369.tio.im.common.packets;

/**
 * <pre>
 **
 * 开始直播响应
 * </pre>
 *
 * Protobuf type {@code BeginToLiveRespBody}
 */
public  final class BeginToLiveRespBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BeginToLiveRespBody)
    BeginToLiveRespBodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BeginToLiveRespBody.newBuilder() to construct.
  private BeginToLiveRespBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BeginToLiveRespBody() {
    time_ = 0L;
    liveId_ = 0L;
    rtmpPublishUrl_ = "";
    rtmpLiveUrl_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BeginToLiveRespBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            time_ = input.readInt64();
            break;
          }
          case 16: {

            liveId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            rtmpPublishUrl_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            rtmpLiveUrl_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.haotu369.tio.im.common.packets.Chat.internal_static_BeginToLiveRespBody_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.haotu369.tio.im.common.packets.Chat.internal_static_BeginToLiveRespBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.haotu369.tio.im.common.packets.BeginToLiveRespBody.class, com.haotu369.tio.im.common.packets.BeginToLiveRespBody.Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <pre>
   * 消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int LIVEID_FIELD_NUMBER = 2;
  private long liveId_;
  /**
   * <pre>
   * 本次直播id
   * </pre>
   *
   * <code>int64 liveId = 2;</code>
   */
  public long getLiveId() {
    return liveId_;
  }

  public static final int RTMPPUBLISHURL_FIELD_NUMBER = 3;
  private volatile java.lang.Object rtmpPublishUrl_;
  /**
   * <pre>
   * rtmp推流地址
   * </pre>
   *
   * <code>string rtmpPublishUrl = 3;</code>
   */
  public java.lang.String getRtmpPublishUrl() {
    java.lang.Object ref = rtmpPublishUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rtmpPublishUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * rtmp推流地址
   * </pre>
   *
   * <code>string rtmpPublishUrl = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRtmpPublishUrlBytes() {
    java.lang.Object ref = rtmpPublishUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rtmpPublishUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RTMPLIVEURL_FIELD_NUMBER = 4;
  private volatile java.lang.Object rtmpLiveUrl_;
  /**
   * <pre>
   * rtmp播放地址
   * </pre>
   *
   * <code>string rtmpLiveUrl = 4;</code>
   */
  public java.lang.String getRtmpLiveUrl() {
    java.lang.Object ref = rtmpLiveUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rtmpLiveUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * rtmp播放地址
   * </pre>
   *
   * <code>string rtmpLiveUrl = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRtmpLiveUrlBytes() {
    java.lang.Object ref = rtmpLiveUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rtmpLiveUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
    if (liveId_ != 0L) {
      output.writeInt64(2, liveId_);
    }
    if (!getRtmpPublishUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, rtmpPublishUrl_);
    }
    if (!getRtmpLiveUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rtmpLiveUrl_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    if (liveId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, liveId_);
    }
    if (!getRtmpPublishUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, rtmpPublishUrl_);
    }
    if (!getRtmpLiveUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rtmpLiveUrl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.haotu369.tio.im.common.packets.BeginToLiveRespBody)) {
      return super.equals(obj);
    }
    com.haotu369.tio.im.common.packets.BeginToLiveRespBody other = (com.haotu369.tio.im.common.packets.BeginToLiveRespBody) obj;

    boolean result = true;
    result = result && (getTime()
        == other.getTime());
    result = result && (getLiveId()
        == other.getLiveId());
    result = result && getRtmpPublishUrl()
        .equals(other.getRtmpPublishUrl());
    result = result && getRtmpLiveUrl()
        .equals(other.getRtmpLiveUrl());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + LIVEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLiveId());
    hash = (37 * hash) + RTMPPUBLISHURL_FIELD_NUMBER;
    hash = (53 * hash) + getRtmpPublishUrl().hashCode();
    hash = (37 * hash) + RTMPLIVEURL_FIELD_NUMBER;
    hash = (53 * hash) + getRtmpLiveUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.haotu369.tio.im.common.packets.BeginToLiveRespBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 开始直播响应
   * </pre>
   *
   * Protobuf type {@code BeginToLiveRespBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BeginToLiveRespBody)
      com.haotu369.tio.im.common.packets.BeginToLiveRespBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haotu369.tio.im.common.packets.Chat.internal_static_BeginToLiveRespBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haotu369.tio.im.common.packets.Chat.internal_static_BeginToLiveRespBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haotu369.tio.im.common.packets.BeginToLiveRespBody.class, com.haotu369.tio.im.common.packets.BeginToLiveRespBody.Builder.class);
    }

    // Construct using com.haotu369.tio.im.common.packets.BeginToLiveRespBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      time_ = 0L;

      liveId_ = 0L;

      rtmpPublishUrl_ = "";

      rtmpLiveUrl_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.haotu369.tio.im.common.packets.Chat.internal_static_BeginToLiveRespBody_descriptor;
    }

    public com.haotu369.tio.im.common.packets.BeginToLiveRespBody getDefaultInstanceForType() {
      return com.haotu369.tio.im.common.packets.BeginToLiveRespBody.getDefaultInstance();
    }

    public com.haotu369.tio.im.common.packets.BeginToLiveRespBody build() {
      com.haotu369.tio.im.common.packets.BeginToLiveRespBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.haotu369.tio.im.common.packets.BeginToLiveRespBody buildPartial() {
      com.haotu369.tio.im.common.packets.BeginToLiveRespBody result = new com.haotu369.tio.im.common.packets.BeginToLiveRespBody(this);
      result.time_ = time_;
      result.liveId_ = liveId_;
      result.rtmpPublishUrl_ = rtmpPublishUrl_;
      result.rtmpLiveUrl_ = rtmpLiveUrl_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.haotu369.tio.im.common.packets.BeginToLiveRespBody) {
        return mergeFrom((com.haotu369.tio.im.common.packets.BeginToLiveRespBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.haotu369.tio.im.common.packets.BeginToLiveRespBody other) {
      if (other == com.haotu369.tio.im.common.packets.BeginToLiveRespBody.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.getLiveId() != 0L) {
        setLiveId(other.getLiveId());
      }
      if (!other.getRtmpPublishUrl().isEmpty()) {
        rtmpPublishUrl_ = other.rtmpPublishUrl_;
        onChanged();
      }
      if (!other.getRtmpLiveUrl().isEmpty()) {
        rtmpLiveUrl_ = other.rtmpLiveUrl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.haotu369.tio.im.common.packets.BeginToLiveRespBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.haotu369.tio.im.common.packets.BeginToLiveRespBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long time_ ;
    /**
     * <pre>
     * 消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     * 消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private long liveId_ ;
    /**
     * <pre>
     * 本次直播id
     * </pre>
     *
     * <code>int64 liveId = 2;</code>
     */
    public long getLiveId() {
      return liveId_;
    }
    /**
     * <pre>
     * 本次直播id
     * </pre>
     *
     * <code>int64 liveId = 2;</code>
     */
    public Builder setLiveId(long value) {
      
      liveId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 本次直播id
     * </pre>
     *
     * <code>int64 liveId = 2;</code>
     */
    public Builder clearLiveId() {
      
      liveId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object rtmpPublishUrl_ = "";
    /**
     * <pre>
     * rtmp推流地址
     * </pre>
     *
     * <code>string rtmpPublishUrl = 3;</code>
     */
    public java.lang.String getRtmpPublishUrl() {
      java.lang.Object ref = rtmpPublishUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtmpPublishUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * rtmp推流地址
     * </pre>
     *
     * <code>string rtmpPublishUrl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRtmpPublishUrlBytes() {
      java.lang.Object ref = rtmpPublishUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtmpPublishUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * rtmp推流地址
     * </pre>
     *
     * <code>string rtmpPublishUrl = 3;</code>
     */
    public Builder setRtmpPublishUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rtmpPublishUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtmp推流地址
     * </pre>
     *
     * <code>string rtmpPublishUrl = 3;</code>
     */
    public Builder clearRtmpPublishUrl() {
      
      rtmpPublishUrl_ = getDefaultInstance().getRtmpPublishUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtmp推流地址
     * </pre>
     *
     * <code>string rtmpPublishUrl = 3;</code>
     */
    public Builder setRtmpPublishUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rtmpPublishUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object rtmpLiveUrl_ = "";
    /**
     * <pre>
     * rtmp播放地址
     * </pre>
     *
     * <code>string rtmpLiveUrl = 4;</code>
     */
    public java.lang.String getRtmpLiveUrl() {
      java.lang.Object ref = rtmpLiveUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtmpLiveUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * rtmp播放地址
     * </pre>
     *
     * <code>string rtmpLiveUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRtmpLiveUrlBytes() {
      java.lang.Object ref = rtmpLiveUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtmpLiveUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * rtmp播放地址
     * </pre>
     *
     * <code>string rtmpLiveUrl = 4;</code>
     */
    public Builder setRtmpLiveUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rtmpLiveUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtmp播放地址
     * </pre>
     *
     * <code>string rtmpLiveUrl = 4;</code>
     */
    public Builder clearRtmpLiveUrl() {
      
      rtmpLiveUrl_ = getDefaultInstance().getRtmpLiveUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rtmp播放地址
     * </pre>
     *
     * <code>string rtmpLiveUrl = 4;</code>
     */
    public Builder setRtmpLiveUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rtmpLiveUrl_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BeginToLiveRespBody)
  }

  // @@protoc_insertion_point(class_scope:BeginToLiveRespBody)
  private static final com.haotu369.tio.im.common.packets.BeginToLiveRespBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.haotu369.tio.im.common.packets.BeginToLiveRespBody();
  }

  public static com.haotu369.tio.im.common.packets.BeginToLiveRespBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BeginToLiveRespBody>
      PARSER = new com.google.protobuf.AbstractParser<BeginToLiveRespBody>() {
    public BeginToLiveRespBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BeginToLiveRespBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BeginToLiveRespBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BeginToLiveRespBody> getParserForType() {
    return PARSER;
  }

  public com.haotu369.tio.im.common.packets.BeginToLiveRespBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

