// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.haotu369.tio.im.common.packets;

public interface BeginToLiveRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BeginToLiveRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   * 本次直播id
   * </pre>
   *
   * <code>int64 liveId = 2;</code>
   */
  long getLiveId();

  /**
   * <pre>
   * rtmp推流地址
   * </pre>
   *
   * <code>string rtmpPublishUrl = 3;</code>
   */
  java.lang.String getRtmpPublishUrl();
  /**
   * <pre>
   * rtmp推流地址
   * </pre>
   *
   * <code>string rtmpPublishUrl = 3;</code>
   */
  com.google.protobuf.ByteString
      getRtmpPublishUrlBytes();

  /**
   * <pre>
   * rtmp播放地址
   * </pre>
   *
   * <code>string rtmpLiveUrl = 4;</code>
   */
  java.lang.String getRtmpLiveUrl();
  /**
   * <pre>
   * rtmp播放地址
   * </pre>
   *
   * <code>string rtmpLiveUrl = 4;</code>
   */
  com.google.protobuf.ByteString
      getRtmpLiveUrlBytes();
}
