// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.haotu369.tio.im.common.packets;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Group_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeoLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeoLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinGroupReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JoinGroupReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinGroupRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JoinGroupRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinGroupNotifyRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JoinGroupNotifyRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExitGroupNotifyRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExitGroupNotifyRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientPageReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientPageReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientPageRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientPageRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BeginToLiveReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BeginToLiveReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BeginToLiveRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BeginToLiveRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EndLiveReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EndLiveReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EndLiveRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EndLiveRespBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\"4\n\004User\022\n\n\002id\030\001 \001(\003\022\020\n\010nick" +
      "name\030\002 \001(\t\022\016\n\006avatar\030\003 \001(\t\"T\n\005Group\022\n\n\002i" +
      "d\030\001 \001(\003\022\020\n\010nickname\030\002 \001(\t\022\016\n\006avatar\030\003 \001(" +
      "\t\022\r\n\005total\030\004 \001(\005\022\016\n\006online\030\005 \001(\005\"\266\001\n\006Cli" +
      "ent\022\n\n\002id\030\001 \001(\t\022\n\n\002ip\030\002 \001(\t\022\014\n\004port\030\003 \001(" +
      "\005\022\023\n\004user\030\004 \001(\0132\005.User\022\016\n\006region\030\005 \001(\t\022\021" +
      "\n\tuserAgent\030\006 \001(\t\022\020\n\010operator\030\007 \001(\t\022!\n\013g" +
      "eoLocation\030\010 \001(\0132\014.GeoLocation\022\031\n\007addres" +
      "s\030\t \001(\0132\010.Address\"2\n\013GeoLocation\022\021\n\tlong" +
      "itude\030\001 \001(\001\022\020\n\010latitude\030\002 \001(\001\"\261\001\n\007Addres" +
      "s\022\025\n\raddressDetail\030\001 \001(\t\022\023\n\013addressCode\030" +
      "\002 \001(\t\022\020\n\010province\030\003 \001(\t\022\014\n\004city\030\004 \001(\t\022\020\n" +
      "\010cityCode\030\005 \001(\t\022\020\n\010district\030\006 \001(\t\022\020\n\010tow" +
      "nship\030\007 \001(\t\022\016\n\006street\030\010 \001(\t\022\024\n\014streetNum" +
      "ber\030\t \001(\t\"\335\001\n\013AuthReqBody\022\r\n\005token\030\001 \001(\t" +
      "\022\020\n\010deviceId\030\002 \001(\t\022\013\n\003seq\030\003 \001(\003\022\037\n\ndevic" +
      "eType\030\004 \001(\0162\013.DeviceType\022\013\n\003cid\030\005 \001(\t\022\022\n" +
      "\nappVersion\030\006 \001(\t\022\022\n\ndeviceInfo\030\007 \001(\t\022\014\n" +
      "\004sign\030\010 \001(\t\022!\n\013geoLocation\030\t \001(\0132\014.GeoLo" +
      "cation\022\031\n\007address\030\n \001(\0132\010.Address\"\016\n\014Aut" +
      "hRespBody\"A\n\014LoginReqBody\022\020\n\010username\030\001 " +
      "\001(\t\022\020\n\010password\030\002 \001(\t\022\r\n\005token\030\003 \001(\t\"3\n\r" +
      "LoginRespBody\022\r\n\005token\030\001 \001(\t\022\023\n\004user\030\002 \001" +
      "(\0132\005.User\"!\n\020JoinGroupReqBody\022\r\n\005group\030\001" +
      " \001(\t\"D\n\021JoinGroupRespBody\022 \n\006result\030\001 \001(" +
      "\0162\020.JoinGroupResult\022\r\n\005group\030\002 \001(\t\"A\n\027Jo" +
      "inGroupNotifyRespBody\022\027\n\006client\030\001 \001(\0132\007." +
      "Client\022\r\n\005group\030\002 \001(\t\"A\n\027ExitGroupNotify" +
      "RespBody\022\027\n\006client\030\001 \001(\0132\007.Client\022\r\n\005gro" +
      "up\030\002 \001(\t\"_\n\013ChatReqBody\022\014\n\004time\030\001 \001(\003\022\027\n" +
      "\004type\030\002 \001(\0162\t.ChatType\022\014\n\004text\030\003 \001(\t\022\r\n\005" +
      "group\030\004 \001(\t\022\014\n\004toId\030\005 \001(\t\"\226\001\n\014ChatRespBo" +
      "dy\022\014\n\004time\030\001 \001(\003\022\027\n\004type\030\002 \001(\0162\t.ChatTyp" +
      "e\022\014\n\004text\030\003 \001(\t\022\033\n\nfromClient\030\004 \001(\0132\007.Cl" +
      "ient\022\031\n\010toClient\030\005 \001(\0132\007.Client\022\r\n\005group" +
      "\030\006 \001(\t\022\n\n\002id\030\007 \001(\t\"G\n\021ClientPageReqBody\022" +
      "\021\n\tpageIndex\030\001 \001(\005\022\020\n\010pageSize\030\002 \001(\005\022\r\n\005" +
      "group\030\003 \001(\t\"h\n\022ClientPageRespBody\022\021\n\tpag" +
      "eIndex\030\001 \001(\005\022\020\n\010pageSize\030\002 \001(\005\022\023\n\013record" +
      "Count\030\003 \001(\005\022\030\n\007clients\030\004 \003(\0132\007.Client\"\"\n" +
      "\022BeginToLiveReqBody\022\014\n\004time\030\001 \001(\003\"`\n\023Beg" +
      "inToLiveRespBody\022\014\n\004time\030\001 \001(\003\022\016\n\006liveId" +
      "\030\002 \001(\003\022\026\n\016rtmpPublishUrl\030\003 \001(\t\022\023\n\013rtmpLi" +
      "veUrl\030\004 \001(\t\"\036\n\016EndLiveReqBody\022\014\n\004time\030\001 " +
      "\001(\003\"/\n\017EndLiveRespBody\022\014\n\004time\030\001 \001(\003\022\016\n\006" +
      "liveId\030\002 \001(\003*g\n\nDeviceType\022\027\n\023DEVICE_TYP" +
      "E_UNKNOWN\020\000\022\022\n\016DEVICE_TYPE_PC\020\001\022\027\n\023DEVIC" +
      "E_TYPE_ANDROID\020\002\022\023\n\017DEVICE_TYPE_IOS\020\003*\226\005" +
      "\n\007Command\022\023\n\017COMMAND_UNKNOWN\020\000\022\031\n\025COMMAN" +
      "D_HANDSHAKE_REQ\020\001\022\032\n\026COMMAND_HANDSHAKE_R" +
      "ESP\020\002\022\024\n\020COMMAND_AUTH_REQ\020\003\022\025\n\021COMMAND_A" +
      "UTH_RESP\020\004\022\032\n\026COMMAND_JOIN_GROUP_REQ\020\005\022\033" +
      "\n\027COMMAND_JOIN_GROUP_RESP\020\006\022\"\n\036COMMAND_J" +
      "OIN_GROUP_NOTIFY_RESP\020\007\022\"\n\036COMMAND_EXIT_" +
      "GROUP_NOTIFY_RESP\020\010\022\024\n\020COMMAND_CHAT_REQ\020" +
      "\t\022\025\n\021COMMAND_CHAT_RESP\020\n\022\032\n\026COMMAND_STAR" +
      "T_SHOW_REQ\020\013\022\033\n\027COMMAND_START_SHOW_RESP\020" +
      "\014\022\030\n\024COMMAND_END_SHOW_REQ\020\r\022 \n\034COMMAND_E" +
      "ND_SHOW_NOTIFY_RESP\020\016\022\031\n\025COMMAND_HEARTBE" +
      "AT_REQ\020\017\022\032\n\026COMMAND_HEARTBEAT_RESP\020\020\022\025\n\021" +
      "COMMAND_CLOSE_REQ\020\021\022\033\n\027COMMAND_CLIENT_PA" +
      "GE_REQ\020\022\022\034\n\030COMMAND_CLIENT_PAGE_RESP\020\023\022\025" +
      "\n\021COMMAND_LOGIN_REQ\020\024\022\026\n\022COMMAND_LOGIN_R" +
      "ESP\020\025\022\032\n\026COMMAND_CANCEL_MSG_REQ\020\026\022\033\n\027COM" +
      "MAND_CANCEL_MSG_RESP\020\027*\315\001\n\017JoinGroupResu" +
      "lt\022\035\n\031JOIN_GROUP_RESULT_UNKNOWN\020\000\022\030\n\024JOI" +
      "N_GROUP_RESULT_OK\020\001\022\037\n\033JOIN_GROUP_RESULT" +
      "_NOT_EXIST\020\002\022 \n\034JOIN_GROUP_RESULT_GROUP_" +
      "FULL\020\003\022\"\n\036JOIN_GROUP_RESULT_IN_BLACKLIST" +
      "\020\004\022\032\n\026JOIN_GROUP_RESULT_KICK\020\005*N\n\010ChatTy" +
      "pe\022\025\n\021CHAT_TYPE_UNKNOWN\020\000\022\024\n\020CHAT_TYPE_P" +
      "UBLIC\020\001\022\025\n\021CHAT_TYPE_PRIVATE\020\002B&\n\"com.ha" +
      "otu369.tio.im.common.packetsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Nickname", "Avatar", });
    internal_static_Group_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Group_descriptor,
        new java.lang.String[] { "Id", "Nickname", "Avatar", "Total", "Online", });
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new java.lang.String[] { "Id", "Ip", "Port", "User", "Region", "UserAgent", "Operator", "GeoLocation", "Address", });
    internal_static_GeoLocation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GeoLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeoLocation_descriptor,
        new java.lang.String[] { "Longitude", "Latitude", });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "AddressDetail", "AddressCode", "Province", "City", "CityCode", "District", "Township", "Street", "StreetNumber", });
    internal_static_AuthReqBody_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AuthReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthReqBody_descriptor,
        new java.lang.String[] { "Token", "DeviceId", "Seq", "DeviceType", "Cid", "AppVersion", "DeviceInfo", "Sign", "GeoLocation", "Address", });
    internal_static_AuthRespBody_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AuthRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthRespBody_descriptor,
        new java.lang.String[] { });
    internal_static_LoginReqBody_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_LoginReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginReqBody_descriptor,
        new java.lang.String[] { "Username", "Password", "Token", });
    internal_static_LoginRespBody_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_LoginRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRespBody_descriptor,
        new java.lang.String[] { "Token", "User", });
    internal_static_JoinGroupReqBody_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_JoinGroupReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JoinGroupReqBody_descriptor,
        new java.lang.String[] { "Group", });
    internal_static_JoinGroupRespBody_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_JoinGroupRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JoinGroupRespBody_descriptor,
        new java.lang.String[] { "Result", "Group", });
    internal_static_JoinGroupNotifyRespBody_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_JoinGroupNotifyRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JoinGroupNotifyRespBody_descriptor,
        new java.lang.String[] { "Client", "Group", });
    internal_static_ExitGroupNotifyRespBody_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ExitGroupNotifyRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExitGroupNotifyRespBody_descriptor,
        new java.lang.String[] { "Client", "Group", });
    internal_static_ChatReqBody_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ChatReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatReqBody_descriptor,
        new java.lang.String[] { "Time", "Type", "Text", "Group", "ToId", });
    internal_static_ChatRespBody_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ChatRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatRespBody_descriptor,
        new java.lang.String[] { "Time", "Type", "Text", "FromClient", "ToClient", "Group", "Id", });
    internal_static_ClientPageReqBody_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_ClientPageReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientPageReqBody_descriptor,
        new java.lang.String[] { "PageIndex", "PageSize", "Group", });
    internal_static_ClientPageRespBody_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_ClientPageRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientPageRespBody_descriptor,
        new java.lang.String[] { "PageIndex", "PageSize", "RecordCount", "Clients", });
    internal_static_BeginToLiveReqBody_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_BeginToLiveReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BeginToLiveReqBody_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_BeginToLiveRespBody_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_BeginToLiveRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BeginToLiveRespBody_descriptor,
        new java.lang.String[] { "Time", "LiveId", "RtmpPublishUrl", "RtmpLiveUrl", });
    internal_static_EndLiveReqBody_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_EndLiveReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EndLiveReqBody_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_EndLiveRespBody_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_EndLiveRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EndLiveRespBody_descriptor,
        new java.lang.String[] { "Time", "LiveId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
