// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.haotu369.tio.im.common.packets;

public interface ClientPageRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientPageRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 第几页
   * </pre>
   *
   * <code>int32 pageIndex = 1;</code>
   */
  int getPageIndex();

  /**
   * <pre>
   * 每页多少条
   * </pre>
   *
   * <code>int32 pageSize = 2;</code>
   */
  int getPageSize();

  /**
   * <pre>
   * 总条数
   * </pre>
   *
   * <code>int32 recordCount = 3;</code>
   */
  int getRecordCount();

  /**
   * <code>repeated .Client clients = 4;</code>
   */
  java.util.List<com.haotu369.tio.im.common.packets.Client> 
      getClientsList();
  /**
   * <code>repeated .Client clients = 4;</code>
   */
  com.haotu369.tio.im.common.packets.Client getClients(int index);
  /**
   * <code>repeated .Client clients = 4;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .Client clients = 4;</code>
   */
  java.util.List<? extends com.haotu369.tio.im.common.packets.ClientOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .Client clients = 4;</code>
   */
  com.haotu369.tio.im.common.packets.ClientOrBuilder getClientsOrBuilder(
      int index);
}
