// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.haotu369.tio.im.common.packets;

/**
 * <pre>
 **
 * 客户端节点信息
 * </pre>
 *
 * Protobuf type {@code Client}
 */
public  final class Client extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Client)
    ClientOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Client.newBuilder() to construct.
  private Client(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Client() {
    id_ = "";
    ip_ = "";
    port_ = 0;
    region_ = "";
    userAgent_ = "";
    operator_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Client(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 24: {

            port_ = input.readInt32();
            break;
          }
          case 34: {
            com.haotu369.tio.im.common.packets.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.haotu369.tio.im.common.packets.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            region_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            userAgent_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            operator_ = s;
            break;
          }
          case 66: {
            com.haotu369.tio.im.common.packets.GeoLocation.Builder subBuilder = null;
            if (geoLocation_ != null) {
              subBuilder = geoLocation_.toBuilder();
            }
            geoLocation_ = input.readMessage(com.haotu369.tio.im.common.packets.GeoLocation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(geoLocation_);
              geoLocation_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.haotu369.tio.im.common.packets.Address.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(com.haotu369.tio.im.common.packets.Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.haotu369.tio.im.common.packets.Chat.internal_static_Client_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.haotu369.tio.im.common.packets.Chat.internal_static_Client_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.haotu369.tio.im.common.packets.Client.class, com.haotu369.tio.im.common.packets.Client.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * ChannelContext id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ChannelContext id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_FIELD_NUMBER = 2;
  private volatile java.lang.Object ip_;
  /**
   * <pre>
   * 客户端ip
   * </pre>
   *
   * <code>string ip = 2;</code>
   */
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 客户端ip
   * </pre>
   *
   * <code>string ip = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 3;
  private int port_;
  /**
   * <pre>
   * 客户端port
   * </pre>
   *
   * <code>int32 port = 3;</code>
   */
  public int getPort() {
    return port_;
  }

  public static final int USER_FIELD_NUMBER = 4;
  private com.haotu369.tio.im.common.packets.User user_;
  /**
   * <pre>
   * 如果没登录过，则为null
   * </pre>
   *
   * <code>.User user = 4;</code>
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <pre>
   * 如果没登录过，则为null
   * </pre>
   *
   * <code>.User user = 4;</code>
   */
  public com.haotu369.tio.im.common.packets.User getUser() {
    return user_ == null ? com.haotu369.tio.im.common.packets.User.getDefaultInstance() : user_;
  }
  /**
   * <pre>
   * 如果没登录过，则为null
   * </pre>
   *
   * <code>.User user = 4;</code>
   */
  public com.haotu369.tio.im.common.packets.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int REGION_FIELD_NUMBER = 5;
  private volatile java.lang.Object region_;
  /**
   * <pre>
   * ip所在地区
   * </pre>
   *
   * <code>string region = 5;</code>
   */
  public java.lang.String getRegion() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      region_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ip所在地区
   * </pre>
   *
   * <code>string region = 5;</code>
   */
  public com.google.protobuf.ByteString
      getRegionBytes() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      region_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERAGENT_FIELD_NUMBER = 6;
  private volatile java.lang.Object userAgent_;
  /**
   * <pre>
   * 浏览器信息
   * </pre>
   *
   * <code>string userAgent = 6;</code>
   */
  public java.lang.String getUserAgent() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userAgent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 浏览器信息
   * </pre>
   *
   * <code>string userAgent = 6;</code>
   */
  public com.google.protobuf.ByteString
      getUserAgentBytes() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userAgent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATOR_FIELD_NUMBER = 7;
  private volatile java.lang.Object operator_;
  /**
   * <pre>
   * ip所属运营商
   * </pre>
   *
   * <code>string operator = 7;</code>
   */
  public java.lang.String getOperator() {
    java.lang.Object ref = operator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operator_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ip所属运营商
   * </pre>
   *
   * <code>string operator = 7;</code>
   */
  public com.google.protobuf.ByteString
      getOperatorBytes() {
    java.lang.Object ref = operator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GEOLOCATION_FIELD_NUMBER = 8;
  private com.haotu369.tio.im.common.packets.GeoLocation geoLocation_;
  /**
   * <pre>
   * 地图定位
   * </pre>
   *
   * <code>.GeoLocation geoLocation = 8;</code>
   */
  public boolean hasGeoLocation() {
    return geoLocation_ != null;
  }
  /**
   * <pre>
   * 地图定位
   * </pre>
   *
   * <code>.GeoLocation geoLocation = 8;</code>
   */
  public com.haotu369.tio.im.common.packets.GeoLocation getGeoLocation() {
    return geoLocation_ == null ? com.haotu369.tio.im.common.packets.GeoLocation.getDefaultInstance() : geoLocation_;
  }
  /**
   * <pre>
   * 地图定位
   * </pre>
   *
   * <code>.GeoLocation geoLocation = 8;</code>
   */
  public com.haotu369.tio.im.common.packets.GeoLocationOrBuilder getGeoLocationOrBuilder() {
    return getGeoLocation();
  }

  public static final int ADDRESS_FIELD_NUMBER = 9;
  private com.haotu369.tio.im.common.packets.Address address_;
  /**
   * <pre>
   * 地址
   * </pre>
   *
   * <code>.Address address = 9;</code>
   */
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <pre>
   * 地址
   * </pre>
   *
   * <code>.Address address = 9;</code>
   */
  public com.haotu369.tio.im.common.packets.Address getAddress() {
    return address_ == null ? com.haotu369.tio.im.common.packets.Address.getDefaultInstance() : address_;
  }
  /**
   * <pre>
   * 地址
   * </pre>
   *
   * <code>.Address address = 9;</code>
   */
  public com.haotu369.tio.im.common.packets.AddressOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
    }
    if (port_ != 0) {
      output.writeInt32(3, port_);
    }
    if (user_ != null) {
      output.writeMessage(4, getUser());
    }
    if (!getRegionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, region_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userAgent_);
    }
    if (!getOperatorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, operator_);
    }
    if (geoLocation_ != null) {
      output.writeMessage(8, getGeoLocation());
    }
    if (address_ != null) {
      output.writeMessage(9, getAddress());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, port_);
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUser());
    }
    if (!getRegionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, region_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userAgent_);
    }
    if (!getOperatorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, operator_);
    }
    if (geoLocation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getGeoLocation());
    }
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getAddress());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.haotu369.tio.im.common.packets.Client)) {
      return super.equals(obj);
    }
    com.haotu369.tio.im.common.packets.Client other = (com.haotu369.tio.im.common.packets.Client) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getIp()
        .equals(other.getIp());
    result = result && (getPort()
        == other.getPort());
    result = result && (hasUser() == other.hasUser());
    if (hasUser()) {
      result = result && getUser()
          .equals(other.getUser());
    }
    result = result && getRegion()
        .equals(other.getRegion());
    result = result && getUserAgent()
        .equals(other.getUserAgent());
    result = result && getOperator()
        .equals(other.getOperator());
    result = result && (hasGeoLocation() == other.hasGeoLocation());
    if (hasGeoLocation()) {
      result = result && getGeoLocation()
          .equals(other.getGeoLocation());
    }
    result = result && (hasAddress() == other.hasAddress());
    if (hasAddress()) {
      result = result && getAddress()
          .equals(other.getAddress());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (37 * hash) + REGION_FIELD_NUMBER;
    hash = (53 * hash) + getRegion().hashCode();
    hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
    hash = (53 * hash) + getUserAgent().hashCode();
    hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
    hash = (53 * hash) + getOperator().hashCode();
    if (hasGeoLocation()) {
      hash = (37 * hash) + GEOLOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getGeoLocation().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.haotu369.tio.im.common.packets.Client parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.haotu369.tio.im.common.packets.Client parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Client parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.haotu369.tio.im.common.packets.Client parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Client parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.haotu369.tio.im.common.packets.Client parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Client parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.haotu369.tio.im.common.packets.Client parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Client parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.haotu369.tio.im.common.packets.Client parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.haotu369.tio.im.common.packets.Client parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.haotu369.tio.im.common.packets.Client parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.haotu369.tio.im.common.packets.Client prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 客户端节点信息
   * </pre>
   *
   * Protobuf type {@code Client}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Client)
      com.haotu369.tio.im.common.packets.ClientOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haotu369.tio.im.common.packets.Chat.internal_static_Client_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haotu369.tio.im.common.packets.Chat.internal_static_Client_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haotu369.tio.im.common.packets.Client.class, com.haotu369.tio.im.common.packets.Client.Builder.class);
    }

    // Construct using com.haotu369.tio.im.common.packets.Client.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      ip_ = "";

      port_ = 0;

      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      region_ = "";

      userAgent_ = "";

      operator_ = "";

      if (geoLocationBuilder_ == null) {
        geoLocation_ = null;
      } else {
        geoLocation_ = null;
        geoLocationBuilder_ = null;
      }
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.haotu369.tio.im.common.packets.Chat.internal_static_Client_descriptor;
    }

    public com.haotu369.tio.im.common.packets.Client getDefaultInstanceForType() {
      return com.haotu369.tio.im.common.packets.Client.getDefaultInstance();
    }

    public com.haotu369.tio.im.common.packets.Client build() {
      com.haotu369.tio.im.common.packets.Client result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.haotu369.tio.im.common.packets.Client buildPartial() {
      com.haotu369.tio.im.common.packets.Client result = new com.haotu369.tio.im.common.packets.Client(this);
      result.id_ = id_;
      result.ip_ = ip_;
      result.port_ = port_;
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      result.region_ = region_;
      result.userAgent_ = userAgent_;
      result.operator_ = operator_;
      if (geoLocationBuilder_ == null) {
        result.geoLocation_ = geoLocation_;
      } else {
        result.geoLocation_ = geoLocationBuilder_.build();
      }
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.haotu369.tio.im.common.packets.Client) {
        return mergeFrom((com.haotu369.tio.im.common.packets.Client)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.haotu369.tio.im.common.packets.Client other) {
      if (other == com.haotu369.tio.im.common.packets.Client.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (!other.getRegion().isEmpty()) {
        region_ = other.region_;
        onChanged();
      }
      if (!other.getUserAgent().isEmpty()) {
        userAgent_ = other.userAgent_;
        onChanged();
      }
      if (!other.getOperator().isEmpty()) {
        operator_ = other.operator_;
        onChanged();
      }
      if (other.hasGeoLocation()) {
        mergeGeoLocation(other.getGeoLocation());
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.haotu369.tio.im.common.packets.Client parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.haotu369.tio.im.common.packets.Client) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * ChannelContext id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ChannelContext id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ChannelContext id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ChannelContext id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ChannelContext id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <pre>
     * 客户端ip
     * </pre>
     *
     * <code>string ip = 2;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 客户端ip
     * </pre>
     *
     * <code>string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 客户端ip
     * </pre>
     *
     * <code>string ip = 2;</code>
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端ip
     * </pre>
     *
     * <code>string ip = 2;</code>
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端ip
     * </pre>
     *
     * <code>string ip = 2;</code>
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <pre>
     * 客户端port
     * </pre>
     *
     * <code>int32 port = 3;</code>
     */
    public int getPort() {
      return port_;
    }
    /**
     * <pre>
     * 客户端port
     * </pre>
     *
     * <code>int32 port = 3;</code>
     */
    public Builder setPort(int value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端port
     * </pre>
     *
     * <code>int32 port = 3;</code>
     */
    public Builder clearPort() {
      
      port_ = 0;
      onChanged();
      return this;
    }

    private com.haotu369.tio.im.common.packets.User user_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.haotu369.tio.im.common.packets.User, com.haotu369.tio.im.common.packets.User.Builder, com.haotu369.tio.im.common.packets.UserOrBuilder> userBuilder_;
    /**
     * <pre>
     * 如果没登录过，则为null
     * </pre>
     *
     * <code>.User user = 4;</code>
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <pre>
     * 如果没登录过，则为null
     * </pre>
     *
     * <code>.User user = 4;</code>
     */
    public com.haotu369.tio.im.common.packets.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.haotu369.tio.im.common.packets.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 如果没登录过，则为null
     * </pre>
     *
     * <code>.User user = 4;</code>
     */
    public Builder setUser(com.haotu369.tio.im.common.packets.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 如果没登录过，则为null
     * </pre>
     *
     * <code>.User user = 4;</code>
     */
    public Builder setUser(
        com.haotu369.tio.im.common.packets.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 如果没登录过，则为null
     * </pre>
     *
     * <code>.User user = 4;</code>
     */
    public Builder mergeUser(com.haotu369.tio.im.common.packets.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.haotu369.tio.im.common.packets.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 如果没登录过，则为null
     * </pre>
     *
     * <code>.User user = 4;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 如果没登录过，则为null
     * </pre>
     *
     * <code>.User user = 4;</code>
     */
    public com.haotu369.tio.im.common.packets.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 如果没登录过，则为null
     * </pre>
     *
     * <code>.User user = 4;</code>
     */
    public com.haotu369.tio.im.common.packets.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.haotu369.tio.im.common.packets.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <pre>
     * 如果没登录过，则为null
     * </pre>
     *
     * <code>.User user = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.haotu369.tio.im.common.packets.User, com.haotu369.tio.im.common.packets.User.Builder, com.haotu369.tio.im.common.packets.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.haotu369.tio.im.common.packets.User, com.haotu369.tio.im.common.packets.User.Builder, com.haotu369.tio.im.common.packets.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private java.lang.Object region_ = "";
    /**
     * <pre>
     * ip所在地区
     * </pre>
     *
     * <code>string region = 5;</code>
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        region_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ip所在地区
     * </pre>
     *
     * <code>string region = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ip所在地区
     * </pre>
     *
     * <code>string region = 5;</code>
     */
    public Builder setRegion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      region_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ip所在地区
     * </pre>
     *
     * <code>string region = 5;</code>
     */
    public Builder clearRegion() {
      
      region_ = getDefaultInstance().getRegion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ip所在地区
     * </pre>
     *
     * <code>string region = 5;</code>
     */
    public Builder setRegionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      region_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userAgent_ = "";
    /**
     * <pre>
     * 浏览器信息
     * </pre>
     *
     * <code>string userAgent = 6;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 浏览器信息
     * </pre>
     *
     * <code>string userAgent = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 浏览器信息
     * </pre>
     *
     * <code>string userAgent = 6;</code>
     */
    public Builder setUserAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userAgent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浏览器信息
     * </pre>
     *
     * <code>string userAgent = 6;</code>
     */
    public Builder clearUserAgent() {
      
      userAgent_ = getDefaultInstance().getUserAgent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浏览器信息
     * </pre>
     *
     * <code>string userAgent = 6;</code>
     */
    public Builder setUserAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userAgent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object operator_ = "";
    /**
     * <pre>
     * ip所属运营商
     * </pre>
     *
     * <code>string operator = 7;</code>
     */
    public java.lang.String getOperator() {
      java.lang.Object ref = operator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ip所属运营商
     * </pre>
     *
     * <code>string operator = 7;</code>
     */
    public com.google.protobuf.ByteString
        getOperatorBytes() {
      java.lang.Object ref = operator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ip所属运营商
     * </pre>
     *
     * <code>string operator = 7;</code>
     */
    public Builder setOperator(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      operator_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ip所属运营商
     * </pre>
     *
     * <code>string operator = 7;</code>
     */
    public Builder clearOperator() {
      
      operator_ = getDefaultInstance().getOperator();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ip所属运营商
     * </pre>
     *
     * <code>string operator = 7;</code>
     */
    public Builder setOperatorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      operator_ = value;
      onChanged();
      return this;
    }

    private com.haotu369.tio.im.common.packets.GeoLocation geoLocation_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.haotu369.tio.im.common.packets.GeoLocation, com.haotu369.tio.im.common.packets.GeoLocation.Builder, com.haotu369.tio.im.common.packets.GeoLocationOrBuilder> geoLocationBuilder_;
    /**
     * <pre>
     * 地图定位
     * </pre>
     *
     * <code>.GeoLocation geoLocation = 8;</code>
     */
    public boolean hasGeoLocation() {
      return geoLocationBuilder_ != null || geoLocation_ != null;
    }
    /**
     * <pre>
     * 地图定位
     * </pre>
     *
     * <code>.GeoLocation geoLocation = 8;</code>
     */
    public com.haotu369.tio.im.common.packets.GeoLocation getGeoLocation() {
      if (geoLocationBuilder_ == null) {
        return geoLocation_ == null ? com.haotu369.tio.im.common.packets.GeoLocation.getDefaultInstance() : geoLocation_;
      } else {
        return geoLocationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 地图定位
     * </pre>
     *
     * <code>.GeoLocation geoLocation = 8;</code>
     */
    public Builder setGeoLocation(com.haotu369.tio.im.common.packets.GeoLocation value) {
      if (geoLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        geoLocation_ = value;
        onChanged();
      } else {
        geoLocationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 地图定位
     * </pre>
     *
     * <code>.GeoLocation geoLocation = 8;</code>
     */
    public Builder setGeoLocation(
        com.haotu369.tio.im.common.packets.GeoLocation.Builder builderForValue) {
      if (geoLocationBuilder_ == null) {
        geoLocation_ = builderForValue.build();
        onChanged();
      } else {
        geoLocationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 地图定位
     * </pre>
     *
     * <code>.GeoLocation geoLocation = 8;</code>
     */
    public Builder mergeGeoLocation(com.haotu369.tio.im.common.packets.GeoLocation value) {
      if (geoLocationBuilder_ == null) {
        if (geoLocation_ != null) {
          geoLocation_ =
            com.haotu369.tio.im.common.packets.GeoLocation.newBuilder(geoLocation_).mergeFrom(value).buildPartial();
        } else {
          geoLocation_ = value;
        }
        onChanged();
      } else {
        geoLocationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 地图定位
     * </pre>
     *
     * <code>.GeoLocation geoLocation = 8;</code>
     */
    public Builder clearGeoLocation() {
      if (geoLocationBuilder_ == null) {
        geoLocation_ = null;
        onChanged();
      } else {
        geoLocation_ = null;
        geoLocationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 地图定位
     * </pre>
     *
     * <code>.GeoLocation geoLocation = 8;</code>
     */
    public com.haotu369.tio.im.common.packets.GeoLocation.Builder getGeoLocationBuilder() {
      
      onChanged();
      return getGeoLocationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 地图定位
     * </pre>
     *
     * <code>.GeoLocation geoLocation = 8;</code>
     */
    public com.haotu369.tio.im.common.packets.GeoLocationOrBuilder getGeoLocationOrBuilder() {
      if (geoLocationBuilder_ != null) {
        return geoLocationBuilder_.getMessageOrBuilder();
      } else {
        return geoLocation_ == null ?
            com.haotu369.tio.im.common.packets.GeoLocation.getDefaultInstance() : geoLocation_;
      }
    }
    /**
     * <pre>
     * 地图定位
     * </pre>
     *
     * <code>.GeoLocation geoLocation = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.haotu369.tio.im.common.packets.GeoLocation, com.haotu369.tio.im.common.packets.GeoLocation.Builder, com.haotu369.tio.im.common.packets.GeoLocationOrBuilder> 
        getGeoLocationFieldBuilder() {
      if (geoLocationBuilder_ == null) {
        geoLocationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.haotu369.tio.im.common.packets.GeoLocation, com.haotu369.tio.im.common.packets.GeoLocation.Builder, com.haotu369.tio.im.common.packets.GeoLocationOrBuilder>(
                getGeoLocation(),
                getParentForChildren(),
                isClean());
        geoLocation_ = null;
      }
      return geoLocationBuilder_;
    }

    private com.haotu369.tio.im.common.packets.Address address_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.haotu369.tio.im.common.packets.Address, com.haotu369.tio.im.common.packets.Address.Builder, com.haotu369.tio.im.common.packets.AddressOrBuilder> addressBuilder_;
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>.Address address = 9;</code>
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>.Address address = 9;</code>
     */
    public com.haotu369.tio.im.common.packets.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? com.haotu369.tio.im.common.packets.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>.Address address = 9;</code>
     */
    public Builder setAddress(com.haotu369.tio.im.common.packets.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>.Address address = 9;</code>
     */
    public Builder setAddress(
        com.haotu369.tio.im.common.packets.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>.Address address = 9;</code>
     */
    public Builder mergeAddress(com.haotu369.tio.im.common.packets.Address value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            com.haotu369.tio.im.common.packets.Address.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>.Address address = 9;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>.Address address = 9;</code>
     */
    public com.haotu369.tio.im.common.packets.Address.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>.Address address = 9;</code>
     */
    public com.haotu369.tio.im.common.packets.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            com.haotu369.tio.im.common.packets.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <pre>
     * 地址
     * </pre>
     *
     * <code>.Address address = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.haotu369.tio.im.common.packets.Address, com.haotu369.tio.im.common.packets.Address.Builder, com.haotu369.tio.im.common.packets.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.haotu369.tio.im.common.packets.Address, com.haotu369.tio.im.common.packets.Address.Builder, com.haotu369.tio.im.common.packets.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Client)
  }

  // @@protoc_insertion_point(class_scope:Client)
  private static final com.haotu369.tio.im.common.packets.Client DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.haotu369.tio.im.common.packets.Client();
  }

  public static com.haotu369.tio.im.common.packets.Client getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Client>
      PARSER = new com.google.protobuf.AbstractParser<Client>() {
    public Client parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Client(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Client> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Client> getParserForType() {
    return PARSER;
  }

  public com.haotu369.tio.im.common.packets.Client getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

