// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.haotu369.tio.im.common.packets;

public interface LoginReqBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginReqBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string token = 3;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 3;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
