package online.shenjian.webservice.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-10-20T17:09:42.386+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://service.cxf.webservice.haotu369.com/", name = "WorkFlowService")
@XmlSeeAlso({ObjectFactory.class})
public interface WorkFlowService {

    @WebMethod
    @RequestWrapper(localName = "execute", targetNamespace = "http://service.cxf.webservice.haotu369.com/", className = "Execute")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://service.cxf.webservice.haotu369.com/", className = "ExecuteResponse")
    public void execute();
}
