// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package online.shenjian.tio.im.common.packets;

public interface AuthRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthRespBody)
    com.google.protobuf.MessageOrBuilder {
}
