// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package online.shenjian.tio.im.common.packets;

public interface GeoLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GeoLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 经度
   * </pre>
   *
   * <code>double longitude = 1;</code>
   */
  double getLongitude();

  /**
   * <pre>
   * 纬度
   * </pre>
   *
   * <code>double latitude = 2;</code>
   */
  double getLatitude();
}
