// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package online.shenjian.tio.im.common.packets;

public interface GroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Group)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 群组ID
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>string nickname = 2;</code>
   */
  java.lang.String getNickname();
  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>string nickname = 2;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <pre>
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <pre>
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <pre>
   * 群组总人数
   * </pre>
   *
   * <code>int32 total = 4;</code>
   */
  int getTotal();

  /**
   * <pre>
   * 群组在线人数
   * </pre>
   *
   * <code>int32 online = 5;</code>
   */
  int getOnline();
}
