// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package online.shenjian.tio.im.common.packets;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>string nickname = 2;</code>
   */
  java.lang.String getNickname();
  /**
   * <pre>
   * 昵称
   * </pre>
   *
   * <code>string nickname = 2;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <pre>
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <pre>
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();
}
